# Simple workflow for deploying static content to GitHub Pages
name: winget test

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install winget
        uses: Cyberboss/install-winget@v1
      - name: Verify Winget Installation
        run: |
          winget --version

